[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"

[theme]
primaryColor="#4B98FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
baseFontSize=16
font="Inter, sans-serif"
headingFont="Inter, sans-serif"

[client]
showErrorDetails="type"
toolbarMode="auto"

[server]
port=8501
headless=false
fileWatcherType="auto"
maxUploadSize=50
enableStaticServing=true
disconnectedSessionTTL = 120

[browser]
gatherUsageStats=false

[secrets]
files = []